version: '3.8'

services:
  # 1. Сервис реляционной СУБД
  db:
    image: postgres:15-alpine
    container_name: kinotavr_postgres_db
    restart: always
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: super_secure_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  # 2. Сервис основного API Бэкенда
  backend:
    build: ./backend
    container_name: kinotavr_backend_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=movies_db
      - DB_USER=user_admin
      - DB_PASSWORD=super_secure_password
    depends_on:
      - db

  # 3. Сервис автоматического наполнителя базы (парсера)
  parser:
    build: ./parser
    container_name: kinotavr_db_filler
    environment:
      - DB_HOST=db
      - DB_NAME=movies_db
      - DB_USER=user_admin
      - DB_PASSWORD=super_secure_password
    depends_on:
      - db

volumes:
  pgdata: